# Generated by Django 2.2 on 2021-08-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detector', '0002_auto_20210820_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='nombre1',
            new_name='nombre',
        ),
    ]
